# Generated by Django 4.1 on 2022-08-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='puesto',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
